// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2846.TestRobot;

import org.usfirst.frc2846.TestRobot.util.WrappedSpeedController;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon chassisleftFront;
    public static CANTalon chassisrightFront;
    public static CANTalon chassisleftRear;
    public static CANTalon chassisrightRear;
    public static RobotDrive chassisrobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisleftFront = new CANTalon(2);
        LiveWindow.addActuator("Chassis", "leftFront", chassisleftFront);
        
        chassisrightFront = new CANTalon(3);
        LiveWindow.addActuator("Chassis", "rightFront", chassisrightFront);
        
        chassisleftRear = new CANTalon(4);
        LiveWindow.addActuator("Chassis", "leftRear", chassisleftRear);
        
        chassisrightRear = new CANTalon(5);
        LiveWindow.addActuator("Chassis", "rightRear", chassisrightRear);
        
        chassisrobotDrive = new RobotDrive(
        		new WrappedSpeedController(chassisleftFront, "leftFront"), 
        		new WrappedSpeedController(chassisleftRear, "leftRear"),
        		new WrappedSpeedController(chassisrightFront, "rightFront"),
        		new WrappedSpeedController(chassisrightRear, "rightRear"));
        
        chassisrobotDrive.setSafetyEnabled(true);
        chassisrobotDrive.setExpiration(0.1);
        chassisrobotDrive.setSensitivity(0.5);
        chassisrobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
