// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2846.TestRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon chassisCANTalon1;
    public static CANTalon chassisCANTalon2;
    public static CANTalon chassisCANTalon3;
    public static CANTalon chassisCANTalon4;
    public static RobotDrive chassisRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisCANTalon1 = new CANTalon(5);
        LiveWindow.addActuator("Chassis", "CAN Talon 1", chassisCANTalon1);
        
        chassisCANTalon2 = new CANTalon(3);
        LiveWindow.addActuator("Chassis", "CAN Talon 2", chassisCANTalon2);
        
        chassisCANTalon3 = new CANTalon(4);
        LiveWindow.addActuator("Chassis", "CAN Talon 3", chassisCANTalon3);
        
        chassisCANTalon4 = new CANTalon(2);
        LiveWindow.addActuator("Chassis", "CAN Talon 4", chassisCANTalon4);
        
        chassisRobotDrive41 = new RobotDrive(chassisCANTalon4, chassisCANTalon3,
              chassisCANTalon2, chassisCANTalon1);
        
        chassisRobotDrive41.setSafetyEnabled(true);
        chassisRobotDrive41.setExpiration(0.1);
        chassisRobotDrive41.setSensitivity(0.5);
        chassisRobotDrive41.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
